# Generated by Django 4.2.4 on 2023-11-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
