# Generated by Django 4.2.4 on 2023-12-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaitem',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
