# Generated by Django 4.2.4 on 2023-12-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_pizzaitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='readiness',
            field=models.BooleanField(default=False, verbose_name='готвность'),
        ),
        migrations.AlterField(
            model_name='pizzaitem',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='цена'),
        ),
    ]
